FROM cassandra:latest
ADD schema.cql schema.cql
# COPY *.cql /docker-entrypoint-initdb.d/

# COPY entrypoint.sh /
# RUN chmod a+x entrypoint.sh
# ENTRYPOINT ["/entrypoint.sh"]
# CMD ["cassandra", "-f"]